spring.application.name=proxismwo
spring.datasource.url=jdbc:mariadb://localhost:3306/proxismwo
spring.datasource.username=proxismwo
spring.datasource.password=_6V6@9"5e55N
spring.jpa.hibernate.ddl-auto=update

axon.axonserver.enabled=false